import type { ProductVariantPublic } from '@remak/shared/contracts/product';

/**
 * Bộ dữ liệu mẫu chuẩn thực tế cho Tấm Chống Cháy Remak® FireOFF MgO
 * Sử dụng khi CMS / API chưa nhập dữ liệu variants (variants: []).
 */
export const FALLBACK_MGO_VARIANTS: ProductVariantPublic[] = [
  {
    id: 'mgo-var-5mm',
    sku: 'MGO-05-STD',
    label: 'Tấm MgO 5mm (Trần & Ốp vách)',
    recommendedUse: 'Trần chìm, trần thả chịu ẩm, ốp hoàn thiện nội thất chống cháy',
    thicknessMm: 5,
    widthMm: 1220,
    lengthMm: 2440,
    areaM2: 2.977,
    weightKg: 15.6,
    densityKgM3: 1050,
    fireRatingMinMinutes: 30,
    fireRatingMaxMinutes: 45,
    fireRatingLabel: 'EI 30 - EI 45 (Chuẩn A1)',
    flexuralMinMpa: 15,
    isPopular: false,
    isDefault: false,
    priceMode: 'PUBLIC',
    priceVnd: 145000,
    compareAtPriceVnd: 165000,
    discountPercent: 12,
    saleUnit: 'SHEET',
    priceValidUntil: null,
    stockStatus: 'IN_STOCK',
    leadTimeDays: 0,
    minOrderQty: 10,
  },
  {
    id: 'mgo-var-8mm',
    sku: 'MGO-08-DUCT',
    label: 'Tấm MgO 8mm (Bọc ống gió PCCC)',
    recommendedUse: 'Bọc bảo vệ ống gió hút khói sự cố, vách ngăn chống cháy EI 45 - 60',
    thicknessMm: 8,
    widthMm: 1220,
    lengthMm: 2440,
    areaM2: 2.977,
    weightKg: 24.8,
    densityKgM3: 1050,
    fireRatingMinMinutes: 45,
    fireRatingMaxMinutes: 60,
    fireRatingLabel: 'EI 45 - EI 60 (Chuẩn A1)',
    flexuralMinMpa: 16,
    isPopular: true,
    isDefault: true,
    priceMode: 'PUBLIC',
    priceVnd: 215000,
    compareAtPriceVnd: 245000,
    discountPercent: 12,
    saleUnit: 'SHEET',
    priceValidUntil: null,
    stockStatus: 'IN_STOCK',
    leadTimeDays: 0,
    minOrderQty: 10,
  },
  {
    id: 'mgo-var-10mm',
    sku: 'MGO-10-WALL',
    label: 'Tấm MgO 10mm (Vách ngăn EI 60 - EI 90)',
    recommendedUse: 'Vách ngăn chống cháy kho xưởng, phòng karaoke, vũ trường tiêu âm',
    thicknessMm: 10,
    widthMm: 1220,
    lengthMm: 2440,
    areaM2: 2.977,
    weightKg: 31.0,
    densityKgM3: 1050,
    fireRatingMinMinutes: 60,
    fireRatingMaxMinutes: 90,
    fireRatingLabel: 'EI 60 - EI 90 (Chuẩn A1)',
    flexuralMinMpa: 18,
    isPopular: true,
    isDefault: false,
    priceMode: 'PUBLIC',
    priceVnd: 265000,
    compareAtPriceVnd: 295000,
    discountPercent: 10,
    saleUnit: 'SHEET',
    priceValidUntil: null,
    stockStatus: 'IN_STOCK',
    leadTimeDays: 0,
    minOrderQty: 10,
  },
  {
    id: 'mgo-var-12mm',
    sku: 'MGO-12-HEAVY',
    label: 'Tấm MgO 12mm (Vách ngăn & Ống gió EI 120)',
    recommendedUse: 'Vách chống cháy cao cấp EI 120, bọc bảo vệ kết cấu thép chịu lực',
    thicknessMm: 12,
    widthMm: 1220,
    lengthMm: 2440,
    areaM2: 2.977,
    weightKg: 37.2,
    densityKgM3: 1050,
    fireRatingMinMinutes: 90,
    fireRatingMaxMinutes: 120,
    fireRatingLabel: 'EI 120 (Chuẩn A1)',
    flexuralMinMpa: 20,
    isPopular: false,
    isDefault: false,
    priceMode: 'PUBLIC',
    priceVnd: 320000,
    compareAtPriceVnd: 360000,
    discountPercent: 11,
    saleUnit: 'SHEET',
    priceValidUntil: null,
    stockStatus: 'IN_STOCK',
    leadTimeDays: 0,
    minOrderQty: 10,
  },
  {
    id: 'mgo-var-15mm',
    sku: 'MGO-15-FLOOR',
    label: 'Tấm MgO 15mm (Sàn lửng chịu tải REI 150)',
    recommendedUse: 'Lót sàn chịu lực nhà thép tiền chế, sàn gác lửng, vách chịu tải trọng cao',
    thicknessMm: 15,
    widthMm: 1220,
    lengthMm: 2440,
    areaM2: 2.977,
    weightKg: 46.5,
    densityKgM3: 1050,
    fireRatingMinMinutes: 120,
    fireRatingMaxMinutes: 150,
    fireRatingLabel: 'REI 150 (Chịu lực & Chống cháy)',
    flexuralMinMpa: 22,
    isPopular: false,
    isDefault: false,
    priceMode: 'PUBLIC',
    priceVnd: 395000,
    compareAtPriceVnd: 450000,
    discountPercent: 12,
    saleUnit: 'SHEET',
    priceValidUntil: null,
    stockStatus: 'IN_STOCK',
    leadTimeDays: 1,
    minOrderQty: 5,
  },
  {
    id: 'mgo-var-18mm',
    sku: 'MGO-18-FLOOR',
    label: 'Tấm MgO 18mm (Sàn chịu tải nặng REI 180)',
    recommendedUse: 'Sàn kho bãi hàng nặng, sàn xe nâng nhẹ, vách ngăn chống cháy 3 giờ',
    thicknessMm: 18,
    widthMm: 1220,
    lengthMm: 2440,
    areaM2: 2.977,
    weightKg: 55.8,
    densityKgM3: 1050,
    fireRatingMinMinutes: 150,
    fireRatingMaxMinutes: 180,
    fireRatingLabel: 'REI 180 (Chuẩn PCCC cao nhất)',
    flexuralMinMpa: 25,
    isPopular: false,
    isDefault: false,
    priceMode: 'PUBLIC',
    priceVnd: 470000,
    compareAtPriceVnd: 540000,
    discountPercent: 13,
    saleUnit: 'SHEET',
    priceValidUntil: null,
    stockStatus: 'IN_STOCK',
    leadTimeDays: 1,
    minOrderQty: 5,
  },
];
